export * from "./home/Home";
export * from "./trending/Trending";
export * from "./discover/Discover";
export * from "./tvShows/TvShows";
export * from "./actors/Actors";
export * from "./category/Category";
export * from "./favorites/Favorites";
export * from "./upcoming/Upcoming";
export * from "./notFound/NotFoundPage";
